services:
  postgres-app:
    image: postgres:16-alpine
    container_name: postgres-vendas-01
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_APP}
      - POSTGRES_USER=${POSTGRES_USER_APP}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_APP}
    ports:
      - "${POSTGRES_PORT_APP:-5432}:5432"
    restart: unless-stopped

  python-app:
    image: python:3.12-slim
    container_name: python-vendas-app
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./sql:/app/sql
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_APP=postgres-app
      - POSTGRES_PORT_APP=5432
    depends_on:
      - postgres-app
    command: >
      bash -c "
        pip install -r /app/requirements.txt &&
        echo 'Inicializando banco de dados...' &&
        python src/init_database.py &&
        echo 'Iniciando simulador de vendas...' &&
        python src/sales_simulator.py
      "
    restart: unless-stopped
